### ISSUE TITLE
MVPリリース時の機能について

### ISSUE THREAD

**Issue by mikurikuri11** [mikurikuri1919/Todo-For-7Habits#20]

**Comment by mikurikuri11** [comment]
まず、申し訳ございません。READMEについてLGTM後に何度か勝手に修正してしまい、差分がGitHub上で分からない状態となっています。そのため、以下の文章で差分について詳細に説明させていただきます。
お手数ですが、ご確認いただき、MVPリリース時の機能についてアドバイスを頂きたいです。

- 卒業試験でLGTMをいただいた際のREADME
    ```jsx
    ## 実装を予定している機能
    ### MVP
    * トップページ
    * 会員登録・ログイン
    * ドキュメントページ
    * ToDo一覧
    * ToDo投稿
    * ToDo詳細
    * デフォルトToDo機能（事前に登録しておく）
    * プロフィール設定ページ
    * 管理者ページ
    * LINE通知機能（1週間に一度）
    * レコメンド機能
    
    ### その後の機能
    * ToDo達成率の算出機能
    * ToDo達成率のグラフ、レポート化
    * 算出した達成率でランキングを表示
    * ToDo達成後のボーナス機能
    * 共有機能（OGP）
    * 利用規約
    * プライバシーポリシー
    ```
    
- 開発中に試行錯誤し、MVP直前（現在）のREADME
    
    ```jsx
    ## 実装を予定している機能
    ### MVP
    * トップページ
    * Googleログイン
    * LINEログイン
    * ToDo一覧
    * ToDo投稿
    * ToDo詳細
    * ToDo達成率の算出機能
    * ToDo達成率のLINE通知機能（日次）
    * 利用規約
    * プライバシーポリシー
    
    ### その後の機能
    * 管理者ページ
    * レコメンド機能
    * ドキュメントページ
    * ToDo達成率のグラフ、レポート化
    * ToDo達成後のボーナス機能
    * ユーザー退会機能
    * 共有機能（OGP）
    ```
    
## 上記の各機能について、それぞれ追加、修正、削除した理由
    
### 追加
- LINEログイン
  - LINE通知機能で誰に通知を送信するのかを判定するために、LINEプロバイダーが提供しているユーザーidが必要だったため。
- ユーザー退会機能
   - ユーザーとしては退会機能がないとサービスに対して、不信感を抱く可能性があるため。
    
### 修正
    
- 会員登録・ログイン
  - Googleログインを使用するのであれば、通常の新規会員登録は不要だと判断したため。
- LINE通知機能
  - 1週間に1度ではなく、毎日ユーザーの指定した時間に送信されるほうがユーザーへのリマインダーとして便利だと考えたため。
    
### 削除

- デフォルトToDo機能
  - 需要がないと考えたため。
- 算出した達成率でランキングを表示
  - 需要がないと考えたため。
- プロフィール設定ページ
  - 需要がないと考えたため。
  
 ### その他
    
- 以下の機能をMVPから外しました。理由としてはここまでの実装で予想の2倍ほど時間がかかっており、これ以上の期限延長は厳しいと考えたため。また、ドキュメントページについて、どのようなページを作成するか決めかねているため。
  - ドキュメントページ
  - 管理者ページ
  - レコメンド機能
- その代わり、以下の機能をMVPに入れました。
  - ToDo達成率の算出機能
  - 利用規約
  - プライバシーポリシー
- また、その後の機能についてですが、MVPレビュー受けての機能追加を想定し、現在予定している以外の機能の実装も予定しております。

**Comment by kenchasonakai** [comment]
LINEログインなど高度な機能を盛り込んでいるので良いと思います！
引き続き開発頑張ってください

**Comment by mikurikuri11** [comment]
ご確認ありがとうございます。
がんばります。
