### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [mikurikuri1919/Todo-For-7Habits#21]
@mikurikuri1919 
お疲れ様です！
こちらMVPリリースレビューになります！ご確認ください。

### 技術
ReactやNext.jsなどモダンなフロントエンドのフレームワークを使用したり、Dockerを使った環境構築など技術に対してチャレンジしている姿勢が見えました！

上記を踏まえて、以下FBとなります。

- ディレクトリ構成（componet）が基本となる構成からやや外れている印象がありました。` React コンポーネント設計`などで調べてみてください。（逆に参考にした記事などがあったら共有していただけると嬉しいです。）
- `src/app/page.tsx`はトップページになるかと思うのですが、34行目のリンクでLinkが`/`に設定してあり、`/`→
`/`に遷移してしまいそうですのでご確認をお願いします。
- （READMEに記載してありますが）LINEログイン周りでエラーが起こっているのでご確認をお願いできればと思います。
- また`rubocop`など **本番環境では使わないgem**が`production`の場所に記載されているので`develop`の場所に移動させても良さそうです。

### ユーザビリティ
React、Next.jsを採用しているいるので、動きはとても滑らかな印象でした！その中で感じたことをFBとしてお伝えさせていただきます！
- 背景色が1色ですので統一感がありますが、その反面、リンクが少しわかりにくくなってしまっている印象でした。ボタンとして背景を少し明るくするなど、**リンク**とわかる見せ方にするといいかと思います。
- 「Sidebar」を開くと「Todoが作成できる」と思いますが、客観的に見た場合、「Sidebar」という文言から「Todoを作成する」というアクションが想像しにくいので、「ボタンを押すとTodoが作成できる」ということがわかるような案内にするといいと思いました。
- 第◯の領域というものがどういうものなのか、このアプリで何ができるのかをTopページで案内してあげると、ユーザもその後のアクションに迷いがなくなるかと思います。

以上です！
Todoの作成など、メイン機能はできていると思います！LGTMです！

また上記内容を本番リリースまでに実装する内容に追加をお願いします。その上でスケジュールを立ててみてください。
本番リリースのスケジュール決まりましたら共有をお願いできればと思います。

また質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by mikurikuri11** [comment]
@tmtkzk0823 
お忙しいところ、レビューいただきありがとうございます。
レビューの内容を踏まえ、以下のタスクが必要だと考えました。
また、各タスクに目安の締切日を記載しております。
補足ですが、「ToDo達成率のグラフ、レポート化」以下のタスクは解像度が低く、難易度も高いと思われるため、予定通りにいかない可能性があると思います。その場合、今後の就活と並行して、これらの開発を進める予定です。
お手数ですが、ご確認をお願い致します。

### MVP後
- [x] ToDoカテゴリー機能（12/9） ※現在進行中のため
- [x] 本番環境用gemの配置換え（12/9）
- [x] ボタンの色や名前の調整（12/9）
- [ ] LINEログイン時のエラー解消（12/10）
- [x] ToDo作成時のエラー解消 （12/10）
- [ ] アプリ紹介ぺージの作成（12/11）
- [x] ディレクトリ構成の調整（12/13）
- [ ] ユーザー退会機能（12/14）
- [ ] ToDo達成率のグラフ、レポート化（12/17）
- [ ] 共有機能（OGP）（12/17）
- [ ] ToDo達成後のボーナス機能（12/20）
- [ ] 管理者ページ（12/22）
- [ ] レコメンド機能（12/24）
- [ ] 本リリース（12/24）

**Comment by tmtkzk0823** [comment]
共有ありがとうございます！
上記、日程承知しました！
実装頑張っていきましょう！
